### ISSUE TITLE
RDM log error.

### ISSUE THREAD

**Issue by ShennyUK** [Nik-Potokar/XIVSlothCombo#1245]
Error logs filled up with the following error;

2023-06-09 15:14:00.500 +01:00 [ERR] [XIVSlothCombo] Preset error
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at XIVSlothCombo.Combos.PvE.RDM.RDM_ST_DPS.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\Combos\PvE\RDM.cs:line 134
   at XIVSlothCombo.CustomComboNS.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\CustomCombo\CustomCombo.cs:line 72
   at XIVSlothCombo.Core.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\Core\IconReplacer.cs:line 72

The above ended up creating a 6Gb dalamud log file.

**Comment by k-kz** [comment]
This has been fixed in #1239 and will be in the next update, sorry about the log file!
