### ISSUE TITLE
[MNK] MnkPerfectBalancePlus bug ?

### ISSUE THREAD

**Issue by augporto** [Nik-Potokar/XIVSlothCombo#187]
In the **MnkPerfectBalancePlus** option there's a bug that make the dalamud log file implode , although the function seems to function properly in game working as espected and does not crash it the following keep being printed on the log file:

````
2022-01-26 17:46:27.440 -03:00 [ERR] [XIVSlothCombo] Don't crash the game
System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVSlothComboPlugin.Combos.MnkPerfectBalancePlus.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\Combos\MNK.cs:line 348
   at XIVSlothComboPlugin.Combos.CustomCombo.TryInvoke(UInt32 actionID, UInt32 lastComboActionID, Single comboTime, Byte level, UInt32& newActionID) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\CustomCombo.cs:line 88
   at XIVSlothComboPlugin.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\IconReplacer.cs:line 93
2022-01-26 17:46:27.440 -03:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wMS0yNlQxNzo0NjoyNy40NDA1Njk5LTAzOjAwIiwiSW5mbyI6IlN5c3RlbS5OdWxsUmVmZXJlbmNlRXhjZXB0aW9uOiBPYmplY3QgcmVmZXJlbmNlIG5vdCBzZXQgdG8gYW4gaW5zdGFuY2Ugb2YgYW4gb2JqZWN0LlxyXG4gICBhdCBYSVZTbG90aENvbWJvUGx1Z2luLkNvbWJvcy5NbmtQZXJmZWN0QmFsYW5jZVBsdXMuSW52b2tlKFVJbnQzMiBhY3Rpb25JRCwgVUludDMyIGxhc3RDb21ib01vdmUsIFNpbmdsZSBjb21ib1RpbWUsIEJ5dGUgbGV2ZWwpIGluIEQ6XFxhXFxYSVZTbG90aENvbWJvXFxYSVZTbG90aENvbWJvXFxYSVZTbG90aENvbWJvXFxDb21ib3NcXE1OSy5jczpsaW5lIDM0OFxyXG4gICBhdCBYSVZTbG90aENvbWJvUGx1Z2luLkNvbWJvcy5DdXN0b21Db21iby5UcnlJbnZva2UoVUludDMyIGFjdGlvbklELCBVSW50MzIgbGFzdENvbWJvQWN0aW9uSUQsIFNpbmdsZSBjb21ib1RpbWUsIEJ5dGUgbGV2ZWwsIFVJbnQzMiYgbmV3QWN0aW9uSUQpIGluIEQ6XFxhXFxYSVZTbG90aENvbWJvXFxYSVZTbG90aENvbWJvXFxYSVZTbG90aENvbWJvXFxDdXN0b21Db21iby5jczpsaW5lIDg4XHJcbiAgIGF0IFhJVlNsb3RoQ29tYm9QbHVnaW4uSWNvblJlcGxhY2VyLkdldEljb25EZXRvdXIoSW50UHRyIGFjdGlvbk1hbmFnZXIsIFVJbnQzMiBhY3Rpb25JRCkgaW4gRDpcXGFcXFhJVlNsb3RoQ29tYm9cXFhJVlNsb3RoQ29tYm9cXFhJVlNsb3RoQ29tYm9cXEljb25SZXBsYWNlci5jczpsaW5lIDkzIiwiQ29udGV4dCI6IltYSVZTbG90aENvbWJvXSBEb24ndCBjcmFzaCB0aGUgZ2FtZSJ9
````

I've noticed that yesterday while reactivating the plugins for patch day and saw the log file with a size of 1GB, that part kept being printed ad infinity while the option was chosen on the XIVSlothCombo, disabling it make it stop printing the error as expected.

**Comment by Nik-Potokar** [comment]
A quick fix for this on the user side is to change the log level by opening dev menu `/xldev`
![image](https://user-images.githubusercontent.com/76532587/151255434-a2dc3c0f-365b-49dd-b872-54ac3ef4fa32.png)

**Comment by augporto** [comment]
oh ok , will see to that , thx!
