### ISSUE TITLE
[MNK] Perfect Balance on Main/AoE combo log spam

### ISSUE THREAD

**Issue by Toora** [Nik-Potokar/XIVSlothCombo#576]
Whenever I have either of these enabled, while the game seems to work fine, my dalamud.log file gets spammed hard, easily 25000 lines in a few minutes on a dummy with error level. Probably not a big deal but wanted to mention at least.

> 2022-04-25 05:22:09.458 +02:00 [ERR] [XIVSlothCombo] Don't crash the game
System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVSlothComboPlugin.Combos.MnkAoECombo.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\Combos\MNK.cs:line 143
   at XIVSlothComboPlugin.Combos.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\CustomCombo.cs:line 151
   at XIVSlothComboPlugin.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\IconReplacer.cs:line 77

> 2022-04-25 05:26:57.384 +02:00 [ERR] [XIVSlothCombo] Don't crash the game
System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVSlothComboPlugin.Combos.MnkBootshineCombo.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\Combos\MNK.cs:line 458
   at XIVSlothComboPlugin.Combos.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\CustomCombo.cs:line 151
   at XIVSlothComboPlugin.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\IconReplacer.cs:line 77

**Comment by grimgal** [comment]
#564

**Comment by k-kz** [comment]
Addressed in #564
