### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by thisischrys** [Nik-Potokar/XIVSlothCombo#618]
[dalamud.log](https://github.com/Nik-Potokar/XIVSlothCombo/files/8591264/dalamud.log)

According to Franzbot @ Goat Place Discord XIVSlothCombo is to blame for my recent Crashes To Desktop.
Started yesterday.

Not sure if this is 100% the case, but it seems to happen when I hit escape to back out of windows (retainer) a lot.

**Comment by smark0** [comment]
> 2022-04-29 15:27:20.655 +02:00 [INF] [LOCALPLUGIN] Loading XIVSlothCombo.dll
2022-04-29 15:27:21.011 +02:00 [INF] [LOCALPLUGIN] Finished loading XIVSlothCombo.dll
2022-04-29 15:28:38.611 +02:00 [INF] [LOCALPLUGIN] Unloading XIVSlothCombo.dll
2022-04-29 15:28:38.611 +02:00 [INF] [LOCALPLUGIN] Finished unloading XIVSlothCombo.dll
2022-04-29 15:28:38.611 +02:00 [ERR] [XIVSlothCombo] Don't crash the game
System.ObjectDisposedException: Hook is already disposed
   at Dalamud.Hooking.Hook`1.CheckDisposed() in C:\goatsoft\companysecrets\dalamud\Hooking\Hook.cs:line 261
   at Dalamud.Hooking.Hook`1.get_Original() in C:\goatsoft\companysecrets\dalamud\Hooking\Hook.cs:line 108
   at XIVSlothComboPlugin.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\IconReplacer.cs:line 77
2022-04-29 15:28:38.615 +02:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNC0yOVQxNToyODozOC42MTU0MzQ3KzAyOjAwIiwiSW5mbyI6IlN5c3RlbS5PYmplY3REaXNwb3NlZEV4Y2VwdGlvbjogSG9vayBpcyBhbHJlYWR5IGRpc3Bvc2VkXHJcbiAgIGF0IERhbGFtdWQuSG9va2luZy5Ib29rYDEuQ2hlY2tEaXNwb3NlZCgpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXEhvb2tpbmdcXEhvb2suY3M6bGluZSAyNjFcclxuICAgYXQgRGFsYW11ZC5Ib29raW5nLkhvb2tgMS5nZXRfT3JpZ2luYWwoKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxIb29raW5nXFxIb29rLmNzOmxpbmUgMTA4XHJcbiAgIGF0IFhJVlNsb3RoQ29tYm9QbHVnaW4uSWNvblJlcGxhY2VyLkdldEljb25EZXRvdXIoSW50UHRyIGFjdGlvbk1hbmFnZXIsIFVJbnQzMiBhY3Rpb25JRCkgaW4gRDpcXGFcXFhJVlNsb3RoQ29tYm9cXFhJVlNsb3RoQ29tYm9cXFhJVlNsb3RoQ29tYm9cXEljb25SZXBsYWNlci5jczpsaW5lIDc3IiwiQ29udGV4dCI6IltYSVZTbG90aENvbWJvXSBEb24ndCBjcmFzaCB0aGUgZ2FtZSJ9
2022-04-29 15:35:33.618 +02:00 [INF] --------------------------------------------------------------------------------

I can second this, experienced a random crash with this plugin being the cause as well.

**Comment by thisischrys** [comment]
Nvm it just happened again with the plugin removed.

**Comment by thisischrys** [comment]
Whoops didn't see new issue, I'll leave it open for that.

**Comment by smark0** [comment]
All right, I will keep an eye out on it, if I experience random crashes. Thanks anyways!
