### ISSUE TITLE
[AST] DPS Feature throws errors every few ms

### ISSUE THREAD

**Issue by SkyChotik** [Nik-Potokar/XIVSlothCombo#97]
`--------------------------------
18:39:36.644 | ERR [XIVSlothCombo] Don't crash the game
System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVSlothComboPlugin.Combos.AstrologianDpsFeature.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\Combos\AST.cs:line 198
   at XIVSlothComboPlugin.Combos.CustomCombo.TryInvoke(UInt32 actionID, UInt32 lastComboActionID, Single comboTime, Byte level, UInt32& newActionID) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\CustomCombo.cs:line 87
   at XIVSlothComboPlugin.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\IconReplacer.cs:line 93
--------------------------------`

every 4-5ms it prints this error in the log/console. Feature works fine, it's just hard to check the log for anything else if my job is set to AST and have the feature enabled.

**Comment by Nik-Potokar** [comment]
Should be fixed thanks to @damolitionn 

<3
